### ISSUE TITLE
[Issue]: Getting the error message 'Org.Apache.Kafka.Common.errors.TimeoutException:Topic not present in metadata after 60000 ms'

### ISSUE THREAD

**Issue by Vrithikaarun** [sngular/kloadgen#333]
### What happened?

I am trying to create a kafka test plan with kloadgen - Avro message. first of all I need the timestamp in producer header file to be 13 digits which is now displaying as date+time format now. Also, getting the above mentioned error when running the JMX

### KloadGen Version

KLoadgen 5.2.10

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by Vrithikaarun** [comment]
Can we get into. Quick call now?

Else let me know your feasible time.

**Comment by jemacineiras** [comment]
HI @Vrithikaarun,

There is already a configuration component to add headers into the message for producer.
I attach an Snapshoot pointing to this component.
 <img width="388" alt="Captura de pantalla 2023-02-01 a las 7 57 11" src="https://user-images.githubusercontent.com/68995937/215973009-45f56b80-aa53-4880-95d4-177c72f41b07.png">

About talk with the team, we are a Open Source division at Sngular, where we work in some spare time and give normal asynchronous support. If you need something more specific, like a custom develop, training or help integrating this tool in you workflow, I should point you to our Business Managers.
Let me know which are your needs.

Cheers!

**Comment by jemacineiras** [comment]
We should split these in two, since we are dealing with 2 different things:
— Including headers during production
— The topic error.

Regarding the second one, looks like the topic is not created in the Kafka cluster and the “auto topic creation mode” is disabled there. So probably you need to create the topic before try to publish. If you attach a proper stack trace, we can offer a better answer.
Cheers

**Comment by jemacineiras** [comment]
Closed due inactivity
