### ISSUE TITLE
[Issue]: Failing to load the Test plan

### ISSUE THREAD

**Issue by sushmatshetty** [sngular/kloadgen#377]
### What happened?

I am trying to open a example test plan and getting below error. What am I missing here:

Problem loading XML from:'/Users/sushma.shetty/kafka_load/kloadgen-master/Example-Test-Plan.jmx'. 
Cause:
CannotResolveClassException: com.sngular.kloadgen.config.kafkaheaders.KafkaHeadersConfigElement

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree/com.sngular.kloadgen.config.kafkaheaders.KafkaHeadersConfigElement
line number         : 29
version             : 5.5
-------------------------------

### KloadGen Version

kloadgen-5.6.0

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by jg2devSr** [comment]
Hi [sushmatshetty](https://github.com/sushmatshetty)!
Thank you for your report, we will review this issue and answer you as soon as possible.

**Comment by jg2devSr** [comment]
Hello @sushmatshetty ,
Please can you check that the .jar of the kloadgen plugin (kloadgen-5.6.0.jar) is inside the JMeter binary folder 'lib/ext' ?

Best regards, thanks

**Comment by jemacineiras** [comment]
HI @sushmatshetty,

Had you a chance a chance to follow @jg2devSr advice?

Cheers

**Comment by sushmatshetty** [comment]
Hi @jemacineiras @jg2devSr ,
I reverted to the 5.4.3 version of jmeter and the kloadgen-3.8.2, that worked. When I use the new version I am not able to load the tests. Thank you.

**Comment by jemacineiras** [comment]
Hi @sushmatshetty ,

I just download a new jmeter 5.5 version, with a new build from master and try to open the Example-Test-Plan.jmx from the repo and it works as expected. See the attached snapshots
Here the actual 5.5 with the example loaded and the header component visible.
![Captura de pantalla 2023-06-07 a las 8 02 26](https://github.com/sngular/kloadgen/assets/68995937/44f2c2fd-8a6d-4933-8284-943bea41a902)
Here the latest jar in the right folder in my jmeter copy.
![Captura de pantalla 2023-06-07 a las 8 03 01](https://github.com/sngular/kloadgen/assets/68995937/0d4f8dd2-a9a1-43d6-846f-3d93a4b44aac)
Can you provide the exact steps you are following? I need to be able to reproduce the issue in order to help you.

Cheers

**Comment by sushmatshetty** [comment]
@jemacineiras I followed the steps and was able to successfully launch on my windows laptop. I am not able to do the same on my Mac OS. Is there any additional step for MAC?
Thanks

**Comment by AdrianLagarteraSngular** [comment]
@sushmatshetty In Mac we have the same steps as linux, and works without problem, could you check the if the .jar its in the ext folder, and by the way, try to change by hand the jmx, or put it here and we will give a look in the different OS we have

**Comment by AdrianLagarteraSngular** [comment]
@sushmatshetty We haven't heard from you for a while, were you finally able to get it to work with the directions?

**Comment by AdrianLagartera** [comment]
Closed due a no answer in a month, open it again if the same help is needed.
