### ISSUE TITLE
[Issue]: `sasl.jaas.config` property is not applied

### ISSUE THREAD

**Issue by ChameleonTartu** [sngular/kloadgen#403]
### What happened?

**Initial solution:**

I am using `KLoadGen v5.6.4` with `JMeter v5.6.2`. When I am applying `sass.jaas.config` property into the `KafkaProducer` it gets erased and I don't receive any messages of failures, so no logs from JMeter and no errors. Also, no connection.

I do have a difficulty to debug this. Can you possibly suggest how to connect and debug this issue further?

The type of connection, I am trying to use:
```
bootstrap.servers={broker-urls}
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="{username}" password="{password}";
```

**Second solution:**

Second solution I have tried with `jaas.conf` file,
where it looks:

```
KafkaClient {
 org.apache.kafka.common.security.scram.ScramLoginModule required username="{username}" password="{password}";
};
```
Similar to one from here: https://github.com/hussein-joe/kafka-security-ssl-sasl/blob/master/sasl-scram/secrets/producer_jaas.conf

**Additional info:**
I cannot post JMX files as many details are behind the enterprise, so I stripped all sensitive info and left the configs and rest.

Sample JMX file:
[Kafka_Demo_jmx.txt](https://github.com/sngular/kloadgen/files/12312525/Kafka_Demo_jmx.txt)

Schema:
```
{
   "type":"record",
   "name":"ClientIdentifier",
   "namespace":"com.baeldung.avro",
   "fields":[
      {
         "name":"hostName",
         "type":"string"
      },
      {
         "name":"ipAddress",
         "type":"string"
      }
   ]
}
```

### KloadGen Version

KLoadGen 5.6.4

### Have you added your JMX Testplan or a replica?

- [x] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by amondacaSN** [comment]
Please can you try with the property `java.security.auth.login.config`? It can directly take  the value:

```
KafkaClient {
 org.apache.kafka.common.security.scram.ScramLoginModule required username="{username}" password="{password}";
};
```

or even a path to the config file containing this information.

**Comment by ChameleonTartu** [comment]
@amondacaSN I have tried this mechanism, but the issue is that I still get no logs. I chose "ALL," and I cannot see if the producer sends any requests to Kafka.

- Does it mean that there is no HTTP request ever sent? Do you think it should be sent?
- How do I know that connection is established correctly?
- What steps can I try to make it work/debug further?

**Comment by amondacaSN** [comment]
@ChameleonTartu if you do not see any error log lines, probably this means that the HTTP request has been sent, because error level logs are active by default.
However, if you want to debug something related to KafkaProducer more depth, then you should config KafkaProducer logger in trace level. This can be done by adding this line to the Jmeter log4j2 config file (located in the bin jmeter directory):

    <Logger name="org.apache.kafka.clients.producer" level="trace" />

With this configuration you will see new tace lines related to the KafkaProducer and Sender in the Log Viewer window like this:

TRACE o.a.k.c.p.KafkaProducer: [Producer clientId=] Waking up the sender since topic test_topic partition 0 is either full or getting a new batch
TRACE o.a.k.c.p.i.Sender: [Producer clientId=] Nodes with data ready to send: [localhost:29092 (id: 1001 rack: null)]
TRACE o.a.k.c.p.i.Sender: [Producer clientId=] Sent produce request to 1001: (type=ProduceRequest, acks=1, timeout=30000, partitionRecords=([PartitionProduceData(index=0, records=MemoryRecords(size=127, buffer=java.nio.HeapByteBuffer[pos=0 lim=127 cap=127]))]), transactionalId=''
TRACE o.a.k.c.p.i.Sender: [Producer clientId=] Received produce response from node 1001 with correlation id 3
TRACE o.a.k.c.p.i.ProducerBatch: Successfully produced messages to test_topic-0 with base offset 2.
